---
- name: Remove old docker version
  yum:
    name: 
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Add dnf plugin
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add docker repository
  command: "yum-config-manager --add-repo {{ dockerce_repo_url }}"

- name: Install docker engine
  yum:
    name: "{{ rhel_dockerce_packages }}"
    state: present
...
