---
- name: Install docker python library
  pip:
    name: docker

- name: Start docker engine service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add users to docker group
  user:
    append: yes
    groups: docker
    name: "{{ docker_user }}"

##TODO: reboot host then check with docker ps command
#- name: test docker
#  shell: "newgrp - docker && docker run hello-world"
#  become: yes
#  become_user: "{{ docker_user }}" 
...
