---
- name: Remove old docker version
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Make apt use https
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Get Docker GPG key
  apt_key:
    id: "{{ apt_key_id }}"
    url: "{{ apt_key_url }}"
    state: present

- name: Add repository
  apt_repository:
    repo: "deb [arch={{ arch }}] https://download.docker.com/linux/{{
      ansible_facts.distribution | lower }} {{ ansible_facts.distribution_release }} stable"
    state: present

- name: Install docker engine
  apt:
    name: "{{ apt_dockerce_packages }}"
    state: present
    update_cache: yes
...
